import { useRef, useState } from 'react';
import { useForm, type SubmitHandler } from 'react-hook-form';
import { useQuery } from '@tanstack/react-query';
import { X, UploadCloud, Loader2 } from 'lucide-react';
import { api } from '@/lib/api';
import { useCreateOffer, useUpdateOffer } from '../hooks/useOffers';
import type { AdminOffer } from '../offers-admin.api';

interface OfferFormValues {
  title: string;
  description: string;
  badge: string;
  validFrom: string;
  validTo: string;
  ctaText: string;
  ctaLink: string;
  isActive: boolean;
  /** "" means no room type (hotel-wide), a CUID means a specific type. */
  roomTypeId: string;
}

interface RoomTypeSummary {
  id: string;
  name: string;
}

interface OfferFormDrawerProps {
  initial: AdminOffer | null; // null → create mode
  onClose: () => void;
}

/**
 * OfferFormDrawer — right-side slide-over for creating or editing an offer.
 *
 * 2026-05-28 — Filesystem-first storage refactor:
 *  - No more 3-step presigned URL pipeline. Image upload is a single
 *    multipart POST/PATCH carrying the selected File + form fields.
 *  - The selected file lives in component state; the server-side filename
 *    is generated by StorageService on the API and returned in the response.
 *  - On edit, the image is optional — leave it unchanged to keep the
 *    existing imageKey.
 *
 * MOUNTING CONTRACT: parent mounts conditionally so this component remounts
 * on every open, letting us initialise state directly from props without
 * the "setState in effect" anti-pattern.
 */
export function OfferFormDrawer({ initial, onClose }: OfferFormDrawerProps) {
  const isEdit = initial !== null;
  const { mutateAsync: createOffer, isPending: isCreating } = useCreateOffer();
  const { mutateAsync: updateOffer, isPending: isUpdating } = useUpdateOffer();

  // Fetch room types to populate the optional association selector.
  // Uses the same query key as RoomTypesPage / RoomDrawer for cache sharing.
  const { data: roomTypes = [] } = useQuery<RoomTypeSummary[]>({
    queryKey: ['room-types'],
    queryFn: () =>
      api.get<RoomTypeSummary[]>('/inventory/room-types').then((r) =>
        r.data.filter((rt) => rt.name),
      ),
    staleTime: 60_000,
  });

  // Local file state — the actual upload happens on submit. For edit mode,
  // null means "keep existing image" and we just show the existing preview.
  const [pendingFile, setPendingFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(
    initial?.imageUrl ?? null,
  );
  const [submitError, setSubmitError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<OfferFormValues>({
    defaultValues: {
      title: initial?.title ?? '',
      description: initial?.description ?? '',
      badge: initial?.badge ?? '',
      validFrom: initial?.validFrom ?? '',
      validTo: initial?.validTo ?? '',
      ctaText: initial?.ctaText ?? '',
      ctaLink: initial?.ctaLink ?? '',
      isActive: initial?.isActive ?? true,
      // "" = hotel-wide; CUID = specific type. Direct read from initial — no useEffect needed
      // (component is conditionally mounted, so it remounts fresh on every open).
      roomTypeId: initial?.roomType?.id ?? '',
    },
  });

  const handleFile = (file: File) => {
    setSubmitError(null);
    // Local preview only — the actual upload happens on submit.
    setImagePreview(URL.createObjectURL(file));
    setPendingFile(file);
  };

  const onSubmit: SubmitHandler<OfferFormValues> = async (values) => {
    setSubmitError(null);
    if (!isEdit && !pendingFile) {
      setSubmitError('La imagen es obligatoria.');
      return;
    }
    if (values.validFrom && values.validTo && values.validTo < values.validFrom) {
      setSubmitError('"Válido hasta" debe ser igual o posterior a "Válido desde".');
      return;
    }
    const fields = {
      title: values.title.trim(),
      description: values.description.trim() || null,
      badge: values.badge.trim() || null,
      validFrom: values.validFrom || null,
      validTo: values.validTo || null,
      ctaText: values.ctaText.trim() || null,
      ctaLink: values.ctaLink.trim() || null,
      isActive: values.isActive,
      // "" → clears association (hotel-wide); CUID → links to that type.
      // buildFormData appends "" when null so the backend Zod schema converts it to null.
      roomTypeId: values.roomTypeId || null,
    };
    try {
      if (isEdit && initial) {
        await updateOffer({ id: initial.id, fields, image: pendingFile });
      } else {
        await createOffer({
          fields: { ...fields, title: fields.title },
          image: pendingFile as File,
        });
      }
      onClose();
    } catch (err) {
      const msg =
        (err as { response?: { data?: { message?: string } } })?.response?.data
          ?.message ?? (err instanceof Error ? err.message : 'Error al guardar');
      setSubmitError(typeof msg === 'string' ? msg : 'Error al guardar la oferta');
    }
  };

  const isSaving = isCreating || isUpdating;

  return (
    <>
      {/* Backdrop */}
      <button
        type="button"
        aria-label="Cerrar"
        className="fixed inset-0 z-40 bg-ink-1/30 backdrop-blur-sm"
        onClick={onClose}
      />
      {/* Drawer */}
      <aside className="fixed right-0 top-0 z-50 h-full w-full sm:w-[480px] bg-warm-white border-l border-warm-line shadow-xl flex flex-col">
        <header className="flex items-center justify-between px-5 py-4 border-b border-warm-line">
          <h2 className="font-display text-xl text-ink-1">
            {isEdit ? 'Editar oferta' : 'Nueva oferta'}
          </h2>
          <button
            type="button"
            aria-label="Cerrar"
            onClick={onClose}
            className="text-ink-3 hover:text-ink-1"
          >
            <X className="w-5 h-5" />
          </button>
        </header>

        <form
          onSubmit={handleSubmit(onSubmit)}
          className="flex-1 overflow-y-auto px-5 py-5 flex flex-col gap-5"
        >
          {/* Image */}
          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-ink-1">
              Imagen {isEdit ? '(opcional al editar)' : '*'}
            </label>
            <div
              className="relative w-full aspect-[4/3] rounded-lg overflow-hidden bg-warm-cream border border-dashed border-warm-line flex items-center justify-center"
              role="button"
              tabIndex={0}
              onClick={() => fileInputRef.current?.click()}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') fileInputRef.current?.click();
              }}
            >
              {imagePreview ? (
                <img
                  src={imagePreview}
                  alt="Vista previa"
                  className="absolute inset-0 w-full h-full object-cover"
                />
              ) : (
                <div className="flex flex-col items-center gap-2 text-ink-3 px-4 text-center">
                  <UploadCloud className="w-7 h-7" />
                  <span className="text-sm">Haz clic para subir una imagen</span>
                  <span className="text-xs text-ink-4">JPG, PNG o WebP · máx 5 MB</span>
                </div>
              )}
            </div>
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/avif"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) handleFile(file);
              }}
            />
          </div>

          {/* Title */}
          <div className="flex flex-col gap-1">
            <label htmlFor="offer-title" className="text-sm font-medium text-ink-1">
              Título *
            </label>
            <input
              id="offer-title"
              type="text"
              className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
              {...register('title', { required: true, minLength: 2, maxLength: 200 })}
            />
            {errors.title && (
              <p className="text-xs text-terracotta">Ingresa un título (2-200 caracteres).</p>
            )}
          </div>

          {/* Description */}
          <div className="flex flex-col gap-1">
            <label htmlFor="offer-description" className="text-sm font-medium text-ink-1">
              Descripción
            </label>
            <textarea
              id="offer-description"
              rows={3}
              maxLength={1000}
              className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30 resize-none"
              {...register('description')}
            />
          </div>

          {/* Badge */}
          <div className="flex flex-col gap-1">
            <label htmlFor="offer-badge" className="text-sm font-medium text-ink-1">
              Etiqueta visible (badge)
            </label>
            <input
              id="offer-badge"
              type="text"
              maxLength={40}
              placeholder="Ej: -20%, 2x1, Solo julio"
              className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
              {...register('badge')}
            />
            <p className="text-xs text-ink-3">Aparece como pill encima de la imagen.</p>
          </div>

          {/* Validity range */}
          <div className="grid grid-cols-2 gap-3">
            <div className="flex flex-col gap-1">
              <label htmlFor="offer-valid-from" className="text-sm font-medium text-ink-1">
                Válido desde
              </label>
              <input
                id="offer-valid-from"
                type="date"
                className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
                {...register('validFrom')}
              />
            </div>
            <div className="flex flex-col gap-1">
              <label htmlFor="offer-valid-to" className="text-sm font-medium text-ink-1">
                Válido hasta
              </label>
              <input
                id="offer-valid-to"
                type="date"
                className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
                {...register('validTo')}
              />
            </div>
          </div>

          {/* CTA */}
          <div className="grid grid-cols-1 gap-3">
            <div className="flex flex-col gap-1">
              <label htmlFor="offer-cta-text" className="text-sm font-medium text-ink-1">
                Texto del botón
              </label>
              <input
                id="offer-cta-text"
                type="text"
                maxLength={60}
                placeholder='Por defecto: "Reservar"'
                className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
                {...register('ctaText')}
              />
            </div>
            <div className="flex flex-col gap-1">
              <label htmlFor="offer-cta-link" className="text-sm font-medium text-ink-1">
                Enlace del botón
              </label>
              <input
                id="offer-cta-link"
                type="text"
                maxLength={300}
                placeholder="Opcional. Si está vacío, lleva al flujo de reserva con la oferta."
                className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
                {...register('ctaLink')}
              />
              <p className="text-xs text-ink-3">
                Si es una URL externa (https://…) abrirá en otra pestaña.
              </p>
            </div>
          </div>

          {/* Room type association */}
          <div className="flex flex-col gap-1">
            <label htmlFor="offer-room-type" className="text-sm font-medium text-ink-1">
              Tipo de habitación (opcional)
            </label>
            <select
              id="offer-room-type"
              className="rounded-md border border-warm-line bg-warm-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-terracotta/30"
              {...register('roomTypeId')}
            >
              <option value="">— Sin tipo específico (oferta general) —</option>
              {roomTypes.map((rt) => (
                <option key={rt.id} value={rt.id}>
                  {rt.name}
                </option>
              ))}
            </select>
            <p className="text-xs text-ink-3">
              Si seleccionas un tipo, el CTA preselecciona esa habitación y la oferta mostrará
              {' "Aplica a: <nombre>"'} en el homepage.
            </p>
          </div>

          {/* Active */}
          <div className="flex items-center gap-2">
            <input
              id="offer-active"
              type="checkbox"
              className="accent-terracotta"
              {...register('isActive')}
            />
            <label htmlFor="offer-active" className="text-sm text-ink-1 cursor-pointer">
              Oferta activa (visible en el homepage)
            </label>
          </div>

          {submitError && (
            <div
              role="alert"
              className="rounded-md border border-terracotta/30 bg-terracotta/10 text-terracotta px-3 py-2 text-sm"
            >
              {submitError}
            </div>
          )}
        </form>

        <footer className="px-5 py-4 border-t border-warm-line flex items-center justify-end gap-3">
          <button
            type="button"
            onClick={onClose}
            className="text-sm text-ink-2 hover:text-ink-1 px-3 py-2"
          >
            Cancelar
          </button>
          <button
            type="submit"
            onClick={handleSubmit(onSubmit)}
            disabled={isSaving}
            className="inline-flex items-center gap-2 rounded-md bg-terracotta text-warm-white text-sm font-medium px-4 py-2 hover:bg-terracotta-deep transition-colors disabled:opacity-60"
          >
            {isSaving && <Loader2 className="w-4 h-4 animate-spin" />}
            {isEdit ? 'Guardar cambios' : 'Crear oferta'}
          </button>
        </footer>
      </aside>
    </>
  );
}
