sonar.projectKey=Hotel-ESTOICOS
sonar.projectName=Hotel ESTOICOS
sonar.projectVersion=1.0

sonar.sources=apps/api/src,apps/web/src

sonar.exclusions=**/node_modules/**,**/.turbo/**,**/dist/**,**/build/**,**/coverage/**,**/e2e/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
