sonar.projectKey=hotel-ESTOICOS
sonar.projectName=Hotel ESTOICOS
sonar.projectVersion=1.0

sonar.sources=apps/api/src,apps/web/src

sonar.exclusions=**/node_modules/**,**/.turbo/**,**/dist/**,**/build/**,**/coverage/**,**/e2e/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_b1533d9e41863e54edd5da1d7478a6e15f8a3e8e