// ─── SSE Event union ──────────────────────────────────────────────────────────

export type SseEvent =
  | { type: 'content_delta'; text: string }
  | { type: 'tool_call_start'; toolName: string; toolCallId: string }
  | { type: 'tool_result'; toolName: string; toolCallId: string; result?: unknown; error?: string }
  | { type: 'message_stop'; finishReason: 'stop' | 'length' | 'content_filter' | 'tool_calls' }
  | { type: 'error'; message: string };

// ─── Chat message ─────────────────────────────────────────────────────────────

export interface ToolResultEntry {
  toolName: string;
  toolCallId: string;
  result?: unknown;
  error?: string;
}

export interface ChatMessage {
  /** local uuid generated by crypto.randomUUID() */
  id: string;
  role: 'user' | 'assistant';
  /** Accumulated content_delta text */
  text: string;
  toolResults: ToolResultEntry[];
  isStreaming: boolean;
  isError?: boolean;
  createdAt: string;
}

// ─── Conversation list ────────────────────────────────────────────────────────

export interface ConversationListItem {
  id: string;
  title: string | null;
  createdAt: string;
  lastMessageAt: string | null;
}

export interface ConversationDetail {
  id: string;
  title: string | null;
  messages: Array<{
    id: string;
    role: 'user' | 'assistant';
    content: string;
    createdAt: string;
  }>;
}

// ─── Context panel ────────────────────────────────────────────────────────────

export interface SuggestedAction {
  /** Human-readable button label */
  label: string;
  /** React Router path — NEVER a mutation URL */
  route: string;
}
